package com.edgedo.sys.entity;

import java.io.Serializable;
import java.util.Date;

public class TransitCarBaseinfo {

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 创建时间
	 */
	private Date createTime;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 操作人
	 */
	private String operator;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 操作时间
	 */
	private Date operateTime;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 版本号
	 */
	private String version;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 默认主键
	 */
	private String id;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 序列号
	 */
	private Integer orderNumber;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 创建人姓名
	 */
	private String createUserName;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 创建人ID
	 */
	private String createUserId;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 车牌号
	 */
	private String carPlateNum;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 车架号
	 */
	private String carFrameNum;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 车牌颜色
	 */
	private String carPlateColor;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 道路运输证号
	 */
	private String transitLicenceNum;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 车辆档案编号
	 */
	private String carRecFileCode;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 省份主键
	 */
	private String provinceId;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 省份名称
	 */
	private String provinceName;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 城市主键
	 */
	private String cityId;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 城市名称
	 */
	private String cityName;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 县区主键
	 */
	private String xianquId;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 县区名
	 */
	private String xianquName;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 联系人   车主名
	 */
	private String contactPerson;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 车主手机号
	 */
	private String contactPhone;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 车辆类型
	 */
	private String carFunType;
	/**
	 * 营运类型
	 */
	private String yingyunType;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 国产、进口
	 */
	private String carGcorjk;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 车辆品牌
	 */
	private String carBrandsName;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 车辆型号
	 */
	private String carProductCode;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 总质量
	 */
	private String totalMass;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 核定载货质量
	 */
	private String totalTakeMass;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 准牵引质量
	 */
	private String totalPullMass;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 整备质量
	 */
	private String zhengbeiMass;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 核定载客
	 */
	private String sitPeopleNum;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 轴数
	 */
	private String rollerCount;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 轴距
	 */
	private String rollerWidth;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 底盘型号
	 */
	private String carDpType;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 外廓尺寸-长
	 */
	private double outsizeLength;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 外廓尺寸-宽
	 */
	private double outsizeWidth;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 外廓尺寸-高
	 */
	private double outsizeHeight;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 内廓尺寸-长
	 */
	private double innersizeLength;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 内廓尺寸-宽
	 */
	private double innersizeWidth;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 内廓尺寸-高
	 */
	private double innersizeHeight;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 登记日期
	 */
	private String bookDay;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 发动机号
	 */
	private String enginCode;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 发动机型号
	 */
	private String enginProductCode;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 发动机排量
	 */
	private String enginInOut;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 发动机功率
	 */
	private String enginGonglv;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 排放标准
	 */
	private String paifangLevel;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 电池类型
	 */
	private String batteryType;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 电池型号
	 */
	private String batteryCode;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 电机功率
	 */
	private Double dianjiGonglv;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 动力类型
	 */
	private String dongliType;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 燃料类型
	 */
	private String fuelType;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 罐体容积
	 */
	private Double tankVolume;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 轮胎数
	 */
	private String severalNum;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 轮胎规格
	 */
	private String severalType;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 行车制动方式
	 */
	private String breakeType;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 制动器形式
	 */
	private String breakerSpec;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 制动防抱死系统
	 */
	private String breakAbs;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 变速器类型
	 */
	private String transmissionType;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 缓速器类型
	 */
	private String retarderType;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 空调系统
	 */
	private String airCleanerSys;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 车辆出厂日期
	 */
	private Date carPfoductDate;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 最近一次维修保养日期
	 */
	private Date lastMaintainDate;
	private Date nextMaintainDate;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 最近一次检测定级记录
	 */
	private Date lastTestLevelDate;

	private Date nextTestLevelDate;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 行驶证发证日期
	 */
	private Date licenceIssuingDate;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 营运证发证时间
	 */
	private Date operatingIssuingDate;

	/**
	 * 营运证到期日期
	 */
	private Date operatingStopDate;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 北斗安装日期
	 */
	private Date beidouInstallDate;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 北斗续费日期
	 */
	private Date beidouXufeiDate;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 原北斗运营商
	 */
	private String beidouOraComp;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 北斗运营商主键
	 */
	private String beidouCompId;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 北斗运营商名
	 */
	private String beidouCompName;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 服务费截止日期
	 */
	private Date beidouFuwuEndDate;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 保险信息记录
	 */
	private Date insuranceRecordDate;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 备注
	 */
	private String remark;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 车辆照片
	 */
	private String carPhoto;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 行驶证照片
	 */
	private String carXinshiLicencePhoto;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 道路运输证照片
	 */
	private String roadTransCertiPhoto;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 所属车队
	 */
	private String ownerCarTeamId;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 所属车队名
	 */
	private String ownerCarTeamName;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 所属车主id
	 */
	private String ownerCarPeopleId;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 是否最新(据此推送车主)
	 */
	private String isNew;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 数据状态
	 */
	private String dataState;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 新的版本号
	 */
	private String newVersion;
	/**
	 * 运力来源
	 */
	private String yunliSource;
	/**
	 * 经营组织方式
	 */
	private String jingyingWay;
	/**
	 * 经营范围
	 */
	private String jingyingArea;
	/**
	 * 经济类型
	 */
	private String jingjiType;
	/**
	 * 初次建档时间
	 */
	private Date firstDocTime;
	/**
	 * 额定转速
	 */
	private Double edZhuansu;
	/**
	 * 发动机扭矩
	 */
	private String enginNiuju;
	/**
	 * 额定扭矩转速
	 */
	private Double edNiujuZhuansu;
	/**
	 * 转向形式
	 */
	private String zhuanxiangType;
	/**
	 * 前后轮距
	 */
	private String qhLunju;
	/**
	 * 钢板弹簧数
	 */
	private String gbTanhuangNum;
	/**
	 * 最高时速
	 */
	private Double highSpeed;
	/**
	 * 转向轮转角内
	 */
	private Double zxlNj;
	/**
	 * 转向轮转角外
	 */
	private Double zxlWj;
	/**
	 * 二级维护周期（月）
	 */
	private Double ejwhzq;
	/**
	 * 前悬架结构型式
	 */
	private String qianXuangua;
	/**
	 * 后悬架结构型式
	 */
	private String houXuangua;
	/***
	 * 燃料电喷装置
	 */
	private String rldpZhuangzhi;
	/**
	 * 前照灯制式
	 */
	private String qzdZhishi;
	/**
	 * 驱动形式
	 */
	private String qudongType;
	/**
	 * 车身颜色
	 */
	private String cheshenColor;
	/**
	 * 百公里油耗
	 */
	private Double youhao;
	/**
	 * 制造厂名称
	 */
	private String productorName;
	/**
	 * 北斗定位信息
	 */
	private String beidouLocat;
	/**
	 * 北斗定位精度和纬度
	 */
	private String lnLt;
	/**
	 * 各种统计的到期日期无特别意思
	 */
	private Date daoqiTime;
	/**
	 * 内网主键
	 */
	private Integer vehicleSerial;
	private Integer vehicleManager;
	//北斗续费到期上次提醒时间,保险到期上次提醒时间，营运证到期上次提醒时间，等级评定到期上次提醒时间，二保到期上次提醒时间
	private Date beidouLastRemind,insuranceLastRemind,operatingLastRemind,levelTestLastRemind,maintainLastRemind;

	private String insuranceComp;

	private Date insuranceStopDate;

	private String insuranceContent;
	//车主微信认证状态
	private String wxChezhuState;
	//判断是否是轩易行公司的车
	private String xyxCompCarFlag;

	private Date carDocTime;
	//参数手机验证码:用于传递参数
	private String phoneCode;
	//原车牌号
	private String oraCarPlateNum;
	//原车主
	private String oraContactPerson;
	//是否可见
	private String checkRenzhengFlag;
	//车是否可见
	private String checkRenzhengFlagTeam;

	//经营许可证号
	private String jyCertNumber;

	//正常：1，即将过期:2，已过期：3
	private String baoxianState;

	private Date baoTingStartTime1;

	private Date baoTingEndTime;

	private String baoTingProof;

	//从业人员ID
	private String empId;
	//从业人员姓名
	private String empName;
	//从业资格证号
	private String empCode;
	//联系电话
	private String empPhone;

	public String getEmpId() {
		return empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	public String getEmpName() {
		return empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public String getEmpCode() {
		return empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	public String getEmpPhone() {
		return empPhone;
	}

	public void setEmpPhone(String empPhone) {
		this.empPhone = empPhone;
	}

	public Date getBaoTingStartTime1() {
		return baoTingStartTime1;
	}

	public void setBaoTingStartTime1(Date baoTingStartTime1) {
		this.baoTingStartTime1 = baoTingStartTime1;
	}

	public Date getBaoTingEndTime() {
		return baoTingEndTime;
	}

	public void setBaoTingEndTime(Date baoTingEndTime) {
		this.baoTingEndTime = baoTingEndTime;
	}

	public String getBaoTingProof() {
		return baoTingProof;
	}

	public void setBaoTingProof(String baoTingProof) {
		this.baoTingProof = baoTingProof;
	}

	public String getBaoxianState() {
		return baoxianState;
	}

	public void setBaoxianState(String baoxianState) {
		this.baoxianState = baoxianState;
	}

	public String getJyCertNumber() {
		return jyCertNumber;
	}

	public void setJyCertNumber(String jyCertNumber) {
		this.jyCertNumber = jyCertNumber;
	}

	public String getCheckRenzhengFlagTeam() {
		return checkRenzhengFlagTeam;
	}

	public void setCheckRenzhengFlagTeam(String checkRenzhengFlagTeam) {
		this.checkRenzhengFlagTeam = checkRenzhengFlagTeam;
	}

	public String getCheckRenzhengFlag() {
		return checkRenzhengFlag;
	}

	public void setCheckRenzhengFlag(String checkRenzhengFlag) {
		this.checkRenzhengFlag = checkRenzhengFlag;
	}

	public String getPhoneCode() {
		return phoneCode;
	}

	public void setPhoneCode(String phoneCode) {
		this.phoneCode = phoneCode;
	}

	public Date getCarDocTime() {
		return carDocTime;
	}

	public void setCarDocTime(Date carDocTime) {
		this.carDocTime = carDocTime;
	}

	private Integer vehicleYearCheck;

	private String vehicleICCardID;
	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回创建时间
	 * @return 创建时间
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回操作人
	 * @return 操作人
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回操作时间
	 * @return 操作时间
	 */
	public Date getOperateTime() {
		return operateTime;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回版本号
	 * @return 版本号
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回默认主键
	 * @return 默认主键
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回序列号
	 * @return 序列号
	 */
	public Integer getOrderNumber() {
		return orderNumber;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回创建人姓名
	 * @return 创建人姓名
	 */
	public String getCreateUserName() {
		return createUserName;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回创建人ID
	 * @return 创建人ID
	 */
	public String getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回车牌号
	 * @return 车牌号
	 */
	public String getCarPlateNum() {
		return carPlateNum;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回车架号
	 * @return 车架号
	 */
	public String getCarFrameNum() {
		return carFrameNum;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回车牌颜色
	 * @return 车牌颜色
	 */
	public String getCarPlateColor() {
		return carPlateColor;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回道路运输证号
	 * @return 道路运输证号
	 */
	public String getTransitLicenceNum() {
		return transitLicenceNum;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回车辆档案编号
	 * @return 车辆档案编号
	 */
	public String getCarRecFileCode() {
		return carRecFileCode;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回省份主键
	 * @return 省份主键
	 */
	public String getProvinceId() {
		return provinceId;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回省份名称
	 * @return 省份名称
	 */
	public String getProvinceName() {
		return provinceName;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回城市主键
	 * @return 城市主键
	 */
	public String getCityId() {
		return cityId;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回城市名称
	 * @return 城市名称
	 */
	public String getCityName() {
		return cityName;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回县区主键
	 * @return 县区主键
	 */
	public String getXianquId() {
		return xianquId;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回县区名
	 * @return 县区名
	 */
	public String getXianquName() {
		return xianquName;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回联系人
	 * @return 联系人
	 */
	public String getContactPerson() {
		return contactPerson;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回车主手机号
	 * @return 车主手机号
	 */
	public String getContactPhone() {
		return contactPhone;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回车辆类型
	 * @return 车辆类型
	 */
	public String getCarFunType() {
		return carFunType;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回国产、进口
	 * @return 国产、进口
	 */
	public String getCarGcorjk() {
		return carGcorjk;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回车辆品牌
	 * @return 车辆品牌
	 */
	public String getCarBrandsName() {
		return carBrandsName;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回车辆型号
	 * @return 车辆型号
	 */
	public String getCarProductCode() {
		return carProductCode;
	}



	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回底盘型号
	 * @return 底盘型号
	 */
	public String getCarDpType() {
		return carDpType;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回外廓尺寸-长
	 * @return 外廓尺寸-长
	 */
	public double getOutsizeLength() {
		return outsizeLength;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回外廓尺寸-宽
	 * @return 外廓尺寸-宽
	 */
	public double getOutsizeWidth() {
		return outsizeWidth;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回外廓尺寸-高
	 * @return 外廓尺寸-高
	 */
	public double getOutsizeHeight() {
		return outsizeHeight;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回内廓尺寸-长
	 * @return 内廓尺寸-长
	 */
	public double getInnersizeLength() {
		return innersizeLength;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回内廓尺寸-宽
	 * @return 内廓尺寸-宽
	 */
	public double getInnersizeWidth() {
		return innersizeWidth;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回内廓尺寸-高
	 * @return 内廓尺寸-高
	 */
	public double getInnersizeHeight() {
		return innersizeHeight;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回登记日期
	 * @return 登记日期
	 */
	public String getBookDay() {
		return bookDay;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回发动机号
	 * @return 发动机号
	 */
	public String getEnginCode() {
		return enginCode;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回发动机型号
	 * @return 发动机型号
	 */
	public String getEnginProductCode() {
		return enginProductCode;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回发动机排量
	 * @return 发动机排量
	 */
	public String getEnginInOut() {
		return enginInOut;
	}


	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回排放标准
	 * @return 排放标准
	 */
	public String getPaifangLevel() {
		return paifangLevel;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回电池类型
	 * @return 电池类型
	 */
	public String getBatteryType() {
		return batteryType;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回电池型号
	 * @return 电池型号
	 */
	public String getBatteryCode() {
		return batteryCode;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回电机功率
	 * @return 电机功率
	 */
	public Double getDianjiGonglv() {
		return dianjiGonglv;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回动力类型
	 * @return 动力类型
	 */
	public String getDongliType() {
		return dongliType;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回燃料类型
	 * @return 燃料类型
	 */
	public String getFuelType() {
		return fuelType;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回罐体容积
	 * @return 罐体容积
	 */
	public Double getTankVolume() {
		return tankVolume;
	}



	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回轮胎规格
	 * @return 轮胎规格
	 */
	public String getSeveralType() {
		return severalType;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回行车制动方式
	 * @return 行车制动方式
	 */
	public String getBreakeType() {
		return breakeType;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回制动器形式
	 * @return 制动器形式
	 */
	public String getBreakerSpec() {
		return breakerSpec;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回制动防抱死系统
	 * @return 制动防抱死系统
	 */
	public String getBreakAbs() {
		return breakAbs;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回变速器类型
	 * @return 变速器类型
	 */
	public String getTransmissionType() {
		return transmissionType;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回缓速器类型
	 * @return 缓速器类型
	 */
	public String getRetarderType() {
		return retarderType;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回空调系统
	 * @return 空调系统
	 */
	public String getAirCleanerSys() {
		return airCleanerSys;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回车辆出厂日期
	 * @return 车辆出厂日期
	 */
	public Date getCarPfoductDate() {
		return carPfoductDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回最近一次维修保养日期
	 * @return 最近一次维修保养日期
	 */
	public Date getLastMaintainDate() {
		return lastMaintainDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回最近一次检测定级记录
	 * @return 最近一次检测定级记录
	 */
	public Date getLastTestLevelDate() {
		return lastTestLevelDate;
	}


	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回行驶证发证日期
	 * @return 行驶证发证日期
	 */
	public Date getLicenceIssuingDate() {
		return licenceIssuingDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回营运证发证时间
	 * @return 营运证发证时间
	 */
	public Date getOperatingIssuingDate() {
		return operatingIssuingDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回北斗安装日期
	 * @return 北斗安装日期
	 */
	public Date getBeidouInstallDate() {
		return beidouInstallDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回北斗续费日期
	 * @return 北斗续费日期
	 */
	public Date getBeidouXufeiDate() {
		return beidouXufeiDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回原北斗运营商
	 * @return 原北斗运营商
	 */
	public String getBeidouOraComp() {
		return beidouOraComp;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回北斗运营商主键
	 * @return 北斗运营商主键
	 */
	public String getBeidouCompId() {
		return beidouCompId;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回北斗运营商名
	 * @return 北斗运营商名
	 */
	public String getBeidouCompName() {
		return beidouCompName;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回服务费截止日期
	 * @return 服务费截止日期
	 */
	public Date getBeidouFuwuEndDate() {
		return beidouFuwuEndDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回保险信息记录
	 * @return 保险信息记录
	 */
	public Date getInsuranceRecordDate() {
		return insuranceRecordDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回备注
	 * @return 备注
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回车辆照片
	 * @return 车辆照片
	 */
	public String getCarPhoto() {
		return carPhoto;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回行驶证照片
	 * @return 行驶证照片
	 */
	public String getCarXinshiLicencePhoto() {
		return carXinshiLicencePhoto;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回道路运输证照片
	 * @return 道路运输证照片
	 */
	public String getRoadTransCertiPhoto() {
		return roadTransCertiPhoto;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回所属车队
	 * @return 所属车队
	 */
	public String getOwnerCarTeamId() {
		return ownerCarTeamId;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回所属车队名
	 * @return 所属车队名
	 */
	public String getOwnerCarTeamName() {
		return ownerCarTeamName;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回所属车主id
	 * @return 所属车主id
	 */
	public String getOwnerCarPeopleId() {
		return ownerCarPeopleId;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回是否最新(据此推送车主)
	 * @return 是否最新(据此推送车主)
	 */
	public String getIsNew() {
		return isNew;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回数据状态
	 * @return 数据状态
	 */
	public String getDataState() {
		return dataState;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回新的版本号
	 * @return 新的版本号
	 */
	public String getNewVersion() {
		return newVersion;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置创建时间
	 * @param createTime 创建时间
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置操作人
	 * @param operator 操作人
	 */
	public void setOperator(String operator) {
		if (operator != null) {
			this.operator = operator.trim();
		} else {
			this.operator = operator;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置操作时间
	 * @param operateTime 操作时间
	 */
	public void setOperateTime(Date operateTime) {
		this.operateTime = operateTime;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置版本号
	 * @param version 版本号
	 */
	public void setVersion(String version) {
		if (version != null) {
			this.version = version.trim();
		} else {
			this.version = version;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置默认主键
	 * @param id 默认主键
	 */
	public void setId(String id) {
		if (id != null) {
			this.id = id.trim();
		} else {
			this.id = id;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置序列号
	 * @param orderNumber 序列号
	 */
	public void setOrderNumber(Integer orderNumber) {
		this.orderNumber = orderNumber;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置创建人姓名
	 * @param createUserName 创建人姓名
	 */
	public void setCreateUserName(String createUserName) {
		if (createUserName != null) {
			this.createUserName = createUserName.trim();
		} else {
			this.createUserName = createUserName;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置创建人ID
	 * @param createUserId 创建人ID
	 */
	public void setCreateUserId(String createUserId) {
		if (createUserId != null) {
			this.createUserId = createUserId.trim();
		} else {
			this.createUserId = createUserId;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置车牌号
	 * @param carPlateNum 车牌号
	 */
	public void setCarPlateNum(String carPlateNum) {
		if (carPlateNum != null) {
			this.carPlateNum = carPlateNum.trim();
		} else {
			this.carPlateNum = carPlateNum;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置车架号
	 * @param carFrameNum 车架号
	 */
	public void setCarFrameNum(String carFrameNum) {
		if (carFrameNum != null) {
			this.carFrameNum = carFrameNum.trim();
		} else {
			this.carFrameNum = carFrameNum;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置车牌颜色
	 * @param carPlateColor 车牌颜色
	 */
	public void setCarPlateColor(String carPlateColor) {
		if (carPlateColor != null) {
			this.carPlateColor = carPlateColor.trim();
		} else {
			this.carPlateColor = carPlateColor;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置道路运输证号
	 * @param transitLicenceNum 道路运输证号
	 */
	public void setTransitLicenceNum(String transitLicenceNum) {
		if (transitLicenceNum != null) {
			this.transitLicenceNum = transitLicenceNum.trim();
		} else {
			this.transitLicenceNum = transitLicenceNum;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置车辆档案编号
	 * @param carRecFileCode 车辆档案编号
	 */
	public void setCarRecFileCode(String carRecFileCode) {
		if (carRecFileCode != null) {
			this.carRecFileCode = carRecFileCode.trim();
		} else {
			this.carRecFileCode = carRecFileCode;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置省份主键
	 * @param provinceId 省份主键
	 */
	public void setProvinceId(String provinceId) {
		if (provinceId != null) {
			this.provinceId = provinceId.trim();
		} else {
			this.provinceId = provinceId;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置省份名称
	 * @param provinceName 省份名称
	 */
	public void setProvinceName(String provinceName) {
		if (provinceName != null) {
			this.provinceName = provinceName.trim();
		} else {
			this.provinceName = provinceName;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置城市主键
	 * @param cityId 城市主键
	 */
	public void setCityId(String cityId) {
		if (cityId != null) {
			this.cityId = cityId.trim();
		} else {
			this.cityId = cityId;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置城市名称
	 * @param cityName 城市名称
	 */
	public void setCityName(String cityName) {
		if (cityName != null) {
			this.cityName = cityName.trim();
		} else {
			this.cityName = cityName;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置县区主键
	 * @param xianquId 县区主键
	 */
	public void setXianquId(String xianquId) {
		if (xianquId != null) {
			this.xianquId = xianquId.trim();
		} else {
			this.xianquId = xianquId;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置县区名
	 * @param xianquName 县区名
	 */
	public void setXianquName(String xianquName) {
		if (xianquName != null) {
			this.xianquName = xianquName.trim();
		} else {
			this.xianquName = xianquName;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置联系人
	 * @param contactPerson 联系人
	 */
	public void setContactPerson(String contactPerson) {
		if (contactPerson != null) {
			this.contactPerson = contactPerson.trim();
		} else {
			this.contactPerson = contactPerson;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置车主手机号
	 * @param contactPhone 车主手机号
	 */
	public void setContactPhone(String contactPhone) {
		if (contactPhone != null) {
			this.contactPhone = contactPhone.trim();
		} else {
			this.contactPhone = contactPhone;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置车辆类型
	 * @param carFunType 车辆类型
	 */
	public void setCarFunType(String carFunType) {
		if (carFunType != null) {
			this.carFunType = carFunType.trim();
		} else {
			this.carFunType = carFunType;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置国产、进口
	 * @param carGcorjk 国产、进口
	 */
	public void setCarGcorjk(String carGcorjk) {
		if (carGcorjk != null) {
			this.carGcorjk = carGcorjk.trim();
		} else {
			this.carGcorjk = carGcorjk;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置车辆品牌
	 * @param carBrandsName 车辆品牌
	 */
	public void setCarBrandsName(String carBrandsName) {
		if (carBrandsName != null) {
			this.carBrandsName = carBrandsName.trim();
		} else {
			this.carBrandsName = carBrandsName;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置车辆型号
	 * @param carProductCode 车辆型号
	 */
	public void setCarProductCode(String carProductCode) {
		if (carProductCode != null) {
			this.carProductCode = carProductCode.trim();
		} else {
			this.carProductCode = carProductCode;
		}
	}

	public String getSitPeopleNum() {
		return sitPeopleNum;
	}

	public void setSitPeopleNum(String sitPeopleNum) {
		this.sitPeopleNum = sitPeopleNum;
	}

	public String getRollerCount() {
		return rollerCount;
	}

	public void setRollerCount(String rollerCount) {
		this.rollerCount = rollerCount;
	}

	public String getRollerWidth() {
		return rollerWidth;
	}

	public void setRollerWidth(String rollerWidth) {
		this.rollerWidth = rollerWidth;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置底盘型号
	 * @param carDpType 底盘型号
	 */
	public void setCarDpType(String carDpType) {
		if (carDpType != null) {
			this.carDpType = carDpType.trim();
		} else {
			this.carDpType = carDpType;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置外廓尺寸-长
	 * @param outsizeLength 外廓尺寸-长
	 */
	public void setOutsizeLength(Double outsizeLength) {
		this.outsizeLength = outsizeLength;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置外廓尺寸-宽
	 * @param outsizeWidth 外廓尺寸-宽
	 */
	public void setOutsizeWidth(Double outsizeWidth) {
		this.outsizeWidth = outsizeWidth;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置外廓尺寸-高
	 * @param outsizeHeight 外廓尺寸-高
	 */
	public void setOutsizeHeight(Double outsizeHeight) {
		this.outsizeHeight = outsizeHeight;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置内廓尺寸-长
	 * @param innersizeLength 内廓尺寸-长
	 */
	public void setInnersizeLength(Double innersizeLength) {
		this.innersizeLength = innersizeLength;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置内廓尺寸-宽
	 * @param innersizeWidth 内廓尺寸-宽
	 */
	public void setInnersizeWidth(Double innersizeWidth) {
		this.innersizeWidth = innersizeWidth;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置内廓尺寸-高
	 * @param innersizeHeight 内廓尺寸-高
	 */
	public void setInnersizeHeight(Double innersizeHeight) {
		this.innersizeHeight = innersizeHeight;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置登记日期
	 * @param bookDay 登记日期
	 */
	public void setBookDay(String bookDay) {
		if (bookDay != null) {
			this.bookDay = bookDay.trim();
		} else {
			this.bookDay = bookDay;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置发动机号
	 * @param enginCode 发动机号
	 */
	public void setEnginCode(String enginCode) {
		if (enginCode != null) {
			this.enginCode = enginCode.trim();
		} else {
			this.enginCode = enginCode;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置发动机型号
	 * @param enginProductCode 发动机型号
	 */
	public void setEnginProductCode(String enginProductCode) {
		if (enginProductCode != null) {
			this.enginProductCode = enginProductCode.trim();
		} else {
			this.enginProductCode = enginProductCode;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置发动机排量
	 * @param enginInOut 发动机排量
	 */
	public void setEnginInOut(String enginInOut) {
		if (enginInOut != null) {
			this.enginInOut = enginInOut.trim();
		} else {
			this.enginInOut = enginInOut;
		}
	}

	public String getEnginGonglv() {
		return enginGonglv;
	}

	public void setEnginGonglv(String enginGonglv) {
		this.enginGonglv = enginGonglv;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置排放标准
	 * @param paifangLevel 排放标准
	 */
	public void setPaifangLevel(String paifangLevel) {
		if (paifangLevel != null) {
			this.paifangLevel = paifangLevel.trim();
		} else {
			this.paifangLevel = paifangLevel;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置电池类型
	 * @param batteryType 电池类型
	 */
	public void setBatteryType(String batteryType) {
		if (batteryType != null) {
			this.batteryType = batteryType.trim();
		} else {
			this.batteryType = batteryType;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置电池型号
	 * @param batteryCode 电池型号
	 */
	public void setBatteryCode(String batteryCode) {
		if (batteryCode != null) {
			this.batteryCode = batteryCode.trim();
		} else {
			this.batteryCode = batteryCode;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置电机功率
	 * @param dianjiGonglv 电机功率
	 */
	public void setDianjiGonglv(Double dianjiGonglv) {
		this.dianjiGonglv = dianjiGonglv;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置动力类型
	 * @param dongliType 动力类型
	 */
	public void setDongliType(String dongliType) {
		if (dongliType != null) {
			this.dongliType = dongliType.trim();
		} else {
			this.dongliType = dongliType;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置燃料类型
	 * @param fuelType 燃料类型
	 */
	public void setFuelType(String fuelType) {
		if (fuelType != null) {
			this.fuelType = fuelType.trim();
		} else {
			this.fuelType = fuelType;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置罐体容积
	 * @param tankVolume 罐体容积
	 */
	public void setTankVolume(Double tankVolume) {
		this.tankVolume = tankVolume;
	}

	public String getSeveralNum() {
		return severalNum;
	}

	public void setSeveralNum(String severalNum) {
		this.severalNum = severalNum;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置轮胎规格
	 * @param severalType 轮胎规格
	 */
	public void setSeveralType(String severalType) {
		if (severalType != null) {
			this.severalType = severalType.trim();
		} else {
			this.severalType = severalType;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置行车制动方式
	 * @param breakeType 行车制动方式
	 */
	public void setBreakeType(String breakeType) {
		if (breakeType != null) {
			this.breakeType = breakeType.trim();
		} else {
			this.breakeType = breakeType;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置制动器形式
	 * @param breakerSpec 制动器形式
	 */
	public void setBreakerSpec(String breakerSpec) {
		if (breakerSpec != null) {
			this.breakerSpec = breakerSpec.trim();
		} else {
			this.breakerSpec = breakerSpec;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置制动防抱死系统
	 * @param breakAbs 制动防抱死系统
	 */
	public void setBreakAbs(String breakAbs) {
		if (breakAbs != null) {
			this.breakAbs = breakAbs.trim();
		} else {
			this.breakAbs = breakAbs;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置变速器类型
	 * @param transmissionType 变速器类型
	 */
	public void setTransmissionType(String transmissionType) {
		if (transmissionType != null) {
			this.transmissionType = transmissionType.trim();
		} else {
			this.transmissionType = transmissionType;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置缓速器类型
	 * @param retarderType 缓速器类型
	 */
	public void setRetarderType(String retarderType) {
		if (retarderType != null) {
			this.retarderType = retarderType.trim();
		} else {
			this.retarderType = retarderType;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置空调系统
	 * @param airCleanerSys 空调系统
	 */
	public void setAirCleanerSys(String airCleanerSys) {
		if (airCleanerSys != null) {
			this.airCleanerSys = airCleanerSys.trim();
		} else {
			this.airCleanerSys = airCleanerSys;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置车辆出厂日期
	 * @param carPfoductDate 车辆出厂日期
	 */
	public void setCarPfoductDate(Date carPfoductDate) {
		this.carPfoductDate = carPfoductDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置最近一次维修保养日期
	 * @param lastMaintainDate 最近一次维修保养日期
	 */
	public void setLastMaintainDate(Date lastMaintainDate) {
		this.lastMaintainDate = lastMaintainDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置最近一次检测定级记录
	 * @param lastTestLevelDate 最近一次检测定级记录
	 */
	public void setLastTestLevelDate(Date lastTestLevelDate) {
		this.lastTestLevelDate = lastTestLevelDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置行驶证发证日期
	 * @param licenceIssuingDate 行驶证发证日期
	 */
	public void setLicenceIssuingDate(Date licenceIssuingDate) {
		this.licenceIssuingDate = licenceIssuingDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置营运证发证时间
	 * @param operatingIssuingDate 营运证发证时间
	 */
	public void setOperatingIssuingDate(Date operatingIssuingDate) {
		this.operatingIssuingDate = operatingIssuingDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置北斗安装日期
	 * @param beidouInstallDate 北斗安装日期
	 */
	public void setBeidouInstallDate(Date beidouInstallDate) {
		this.beidouInstallDate = beidouInstallDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置北斗续费日期
	 * @param beidouXufeiDate 北斗续费日期
	 */
	public void setBeidouXufeiDate(Date beidouXufeiDate) {
		this.beidouXufeiDate = beidouXufeiDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置原北斗运营商
	 * @param beidouOraComp 原北斗运营商
	 */
	public void setBeidouOraComp(String beidouOraComp) {
		if (beidouOraComp != null) {
			this.beidouOraComp = beidouOraComp.trim();
		} else {
			this.beidouOraComp = beidouOraComp;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置北斗运营商主键
	 * @param beidouCompId 北斗运营商主键
	 */
	public void setBeidouCompId(String beidouCompId) {
		if (beidouCompId != null) {
			this.beidouCompId = beidouCompId.trim();
		} else {
			this.beidouCompId = beidouCompId;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置北斗运营商名
	 * @param beidouCompName 北斗运营商名
	 */
	public void setBeidouCompName(String beidouCompName) {
		if (beidouCompName != null) {
			this.beidouCompName = beidouCompName.trim();
		} else {
			this.beidouCompName = beidouCompName;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置服务费截止日期
	 * @param beidouFuwuEndDate 服务费截止日期
	 */
	public void setBeidouFuwuEndDate(Date beidouFuwuEndDate) {
		this.beidouFuwuEndDate = beidouFuwuEndDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置保险信息记录
	 * @param insuranceRecordDate 保险信息记录
	 */
	public void setInsuranceRecordDate(Date insuranceRecordDate) {
		this.insuranceRecordDate = insuranceRecordDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置备注
	 * @param remark 备注
	 */
	public void setRemark(String remark) {
		if (remark != null) {
			this.remark = remark.trim();
		} else {
			this.remark = remark;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置车辆照片
	 * @param carPhoto 车辆照片
	 */
	public void setCarPhoto(String carPhoto) {
		if (carPhoto != null) {
			this.carPhoto = carPhoto.trim();
		} else {
			this.carPhoto = carPhoto;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置行驶证照片
	 * @param carXinshiLicencePhoto 行驶证照片
	 */
	public void setCarXinshiLicencePhoto(String carXinshiLicencePhoto) {
		if (carXinshiLicencePhoto != null) {
			this.carXinshiLicencePhoto = carXinshiLicencePhoto.trim();
		} else {
			this.carXinshiLicencePhoto = carXinshiLicencePhoto;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置道路运输证照片
	 * @param roadTransCertiPhoto 道路运输证照片
	 */
	public void setRoadTransCertiPhoto(String roadTransCertiPhoto) {
		if (roadTransCertiPhoto != null) {
			this.roadTransCertiPhoto = roadTransCertiPhoto.trim();
		} else {
			this.roadTransCertiPhoto = roadTransCertiPhoto;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置所属车队
	 * @param ownerCarTeamId 所属车队
	 */
	public void setOwnerCarTeamId(String ownerCarTeamId) {
		if (ownerCarTeamId != null) {
			this.ownerCarTeamId = ownerCarTeamId.trim();
		} else {
			this.ownerCarTeamId = ownerCarTeamId;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置所属车队名
	 * @param ownerCarTeamName 所属车队名
	 */
	public void setOwnerCarTeamName(String ownerCarTeamName) {
		if (ownerCarTeamName != null) {
			this.ownerCarTeamName = ownerCarTeamName.trim();
		} else {
			this.ownerCarTeamName = ownerCarTeamName;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置所属车主id
	 * @param ownerCarPeopleId 所属车主id
	 */
	public void setOwnerCarPeopleId(String ownerCarPeopleId) {
		if (ownerCarPeopleId != null) {
			this.ownerCarPeopleId = ownerCarPeopleId.trim();
		} else {
			this.ownerCarPeopleId = ownerCarPeopleId;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置是否最新(据此推送车主)
	 * @param isNew 是否最新(据此推送车主)
	 */
	public void setIsNew(String isNew) {
		if (isNew != null) {
			this.isNew = isNew.trim();
		} else {
			this.isNew = isNew;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置数据状态
	 * @param dataState 数据状态
	 */
	public void setDataState(String dataState) {
		if (dataState != null) {
			this.dataState = dataState.trim();
		} else {
			this.dataState = dataState;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置新的版本号
	 * @param newVersion 新的版本号
	 */
	public void setNewVersion(String newVersion) {
		if (newVersion != null) {
			this.newVersion = newVersion.trim();
		} else {
			this.newVersion = newVersion;
		}
	}

	public String getYingyunType() {
		return yingyunType;
	}

	public void setYingyunType(String yingyunType) {
		this.yingyunType = yingyunType;
	}

	public Date getOperatingStopDate() {
		return operatingStopDate;
	}

	public void setOperatingStopDate(Date operatingStopDate) {
		this.operatingStopDate = operatingStopDate;
	}

	public String getYunliSource() {
		return yunliSource;
	}

	public void setYunliSource(String yunliSource) {
		this.yunliSource = yunliSource;
	}

	public String getJingyingWay() {
		return jingyingWay;
	}

	public void setJingyingWay(String jingyingWay) {
		this.jingyingWay = jingyingWay;
	}

	public String getJingyingArea() {
		return jingyingArea;
	}

	public void setJingyingArea(String jingyingArea) {
		this.jingyingArea = jingyingArea;
	}

	public String getJingjiType() {
		return jingjiType;
	}

	public void setJingjiType(String jingjiType) {
		this.jingjiType = jingjiType;
	}

	public Date getFirstDocTime() {
		return firstDocTime;
	}

	public void setFirstDocTime(Date firstDocTime) {
		this.firstDocTime = firstDocTime;
	}

	public Double getEdZhuansu() {
		return edZhuansu;
	}

	public void setEdZhuansu(Double edZhuansu) {
		this.edZhuansu = edZhuansu;
	}

	public String getEnginNiuju() {
		return enginNiuju;
	}

	public void setEnginNiuju(String enginNiuju) {
		this.enginNiuju = enginNiuju;
	}

	public Double getEdNiujuZhuansu() {
		return edNiujuZhuansu;
	}

	public void setEdNiujuZhuansu(Double edNiujuZhuansu) {
		this.edNiujuZhuansu = edNiujuZhuansu;
	}

	public String getZhuanxiangType() {
		return zhuanxiangType;
	}

	public void setZhuanxiangType(String zhuanxiangType) {
		this.zhuanxiangType = zhuanxiangType;
	}

	public String getQhLunju() {
		return qhLunju;
	}

	public void setQhLunju(String qhLunju) {
		this.qhLunju = qhLunju;
	}

	public String getGbTanhuangNum() {
		return gbTanhuangNum;
	}

	public void setGbTanhuangNum(String gbTanhuangNum) {
		this.gbTanhuangNum = gbTanhuangNum;
	}

	public Double getHighSpeed() {
		return highSpeed;
	}

	public void setHighSpeed(Double highSpeed) {
		this.highSpeed = highSpeed;
	}

	public Double getZxlNj() {
		return zxlNj;
	}

	public void setZxlNj(Double zxlNj) {
		this.zxlNj = zxlNj;
	}

	public Double getZxlWj() {
		return zxlWj;
	}

	public void setZxlWj(Double zxlWj) {
		this.zxlWj = zxlWj;
	}

	public Double getEjwhzq() {
		return ejwhzq;
	}

	public void setEjwhzq(Double ejwhzq) {
		this.ejwhzq = ejwhzq;
	}

	public String getQianXuangua() {
		return qianXuangua;
	}

	public void setQianXuangua(String qianXuangua) {
		this.qianXuangua = qianXuangua;
	}

	public String getHouXuangua() {
		return houXuangua;
	}

	public void setHouXuangua(String houXuangua) {
		this.houXuangua = houXuangua;
	}

	public String getRldpZhuangzhi() {
		return rldpZhuangzhi;
	}

	public void setRldpZhuangzhi(String rldpZhuangzhi) {
		this.rldpZhuangzhi = rldpZhuangzhi;
	}

	public String getQzdZhishi() {
		return qzdZhishi;
	}

	public void setQzdZhishi(String qzdZhishi) {
		this.qzdZhishi = qzdZhishi;
	}

	public String getQudongType() {
		return qudongType;
	}

	public void setQudongType(String qudongType) {
		this.qudongType = qudongType;
	}

	public String getCheshenColor() {
		return cheshenColor;
	}

	public void setCheshenColor(String cheshenColor) {
		this.cheshenColor = cheshenColor;
	}

	public Double getYouhao() {
		return youhao;
	}

	public void setYouhao(Double youhao) {
		this.youhao = youhao;
	}

	public String getProductorName() {
		return productorName;
	}

	public void setProductorName(String productorName) {
		this.productorName = productorName;
	}

	public String getBeidouLocat() {
		return beidouLocat;
	}

	public void setBeidouLocat(String beidouLocat) {
		this.beidouLocat = beidouLocat;
	}

	public String getLnLt() {
		return lnLt;
	}

	public void setLnLt(String lnLt) {
		this.lnLt = lnLt;
	}

	public Date getDaoqiTime() {
		return daoqiTime;
	}

	public void setDaoqiTime(Date daoqiTime) {
		this.daoqiTime = daoqiTime;
	}

	public Date getNextMaintainDate() {
		return nextMaintainDate;
	}

	public void setNextMaintainDate(Date nextMaintainDate) {
		this.nextMaintainDate = nextMaintainDate;
	}

	public Date getNextTestLevelDate() {
		return nextTestLevelDate;
	}

	public void setNextTestLevelDate(Date nextTestLevelDate) {
		this.nextTestLevelDate = nextTestLevelDate;
	}

	public Integer getVehicleSerial() {
		return vehicleSerial;
	}

	public void setVehicleSerial(Integer vehicleSerial) {
		this.vehicleSerial = vehicleSerial;
	}

	public String getTotalMass() {
		return totalMass;
	}

	public void setTotalMass(String totalMass) {
		this.totalMass = totalMass;
	}

	public String getTotalTakeMass() {
		return totalTakeMass;
	}

	public void setTotalTakeMass(String totalTakeMass) {
		this.totalTakeMass = totalTakeMass;
	}

	public String getTotalPullMass() {
		return totalPullMass;
	}

	public void setTotalPullMass(String totalPullMass) {
		this.totalPullMass = totalPullMass;
	}

	public String getZhengbeiMass() {
		return zhengbeiMass;
	}

	public void setZhengbeiMass(String zhengbeiMass) {
		this.zhengbeiMass = zhengbeiMass;
	}

	public Date getBeidouLastRemind() {
		return beidouLastRemind;
	}

	public void setBeidouLastRemind(Date beidouLastRemind) {
		this.beidouLastRemind = beidouLastRemind;
	}

	public Date getInsuranceLastRemind() {
		return insuranceLastRemind;
	}

	public void setInsuranceLastRemind(Date insuranceLastRemind) {
		this.insuranceLastRemind = insuranceLastRemind;
	}

	public Date getOperatingLastRemind() {
		return operatingLastRemind;
	}

	public void setOperatingLastRemind(Date operatingLastRemind) {
		this.operatingLastRemind = operatingLastRemind;
	}

	public Date getLevelTestLastRemind() {
		return levelTestLastRemind;
	}

	public void setLevelTestLastRemind(Date levelTestLastRemind) {
		this.levelTestLastRemind = levelTestLastRemind;
	}

	public Date getMaintainLastRemind() {
		return maintainLastRemind;
	}

	public void setMaintainLastRemind(Date maintainLastRemind) {
		this.maintainLastRemind = maintainLastRemind;
	}

	public String getInsuranceComp() {
		return insuranceComp;
	}

	public void setInsuranceComp(String insuranceComp) {
		this.insuranceComp = insuranceComp;
	}

	public Date getInsuranceStopDate() {
		return insuranceStopDate;
	}

	public void setInsuranceStopDate(Date insuranceStopDate) {
		this.insuranceStopDate = insuranceStopDate;
	}

	public String getInsuranceContent() {
		return insuranceContent;
	}

	public void setInsuranceContent(String insuranceContent) {
		this.insuranceContent = insuranceContent;
	}

	public String getWxChezhuState() {
		return wxChezhuState;
	}

	public void setWxChezhuState(String wxChezhuState) {
		this.wxChezhuState = wxChezhuState;
	}

	public Integer getVehicleManager() {
		return vehicleManager;
	}

	public void setVehicleManager(Integer vehicleManager) {
		this.vehicleManager = vehicleManager;
	}

	public String getXyxCompCarFlag() {
		return xyxCompCarFlag;
	}

	public void setXyxCompCarFlag(String xyxCompCarFlag) {
		this.xyxCompCarFlag = xyxCompCarFlag;
	}

	public String getOraCarPlateNum() {
		return oraCarPlateNum;
	}

	public void setOraCarPlateNum(String oraCarPlateNum) {
		this.oraCarPlateNum = oraCarPlateNum;
	}

	public String getOraContactPerson() {
		return oraContactPerson;
	}

	public void setOraContactPerson(String oraContactPerson) {
		this.oraContactPerson = oraContactPerson;
	}

	public Integer getVehicleYearCheck() {
		return vehicleYearCheck;
	}

	public void setVehicleYearCheck(Integer vehicleYearCheck) {
		this.vehicleYearCheck = vehicleYearCheck;
	}

	public String getVehicleICCardID() {
		return vehicleICCardID;
	}

	public void setVehicleICCardID(String vehicleICCardID) {
		this.vehicleICCardID = vehicleICCardID;
	}
}